"""users and clients

Revision ID: 66961e25aa7f
Revises: 
Create Date: 2025-01-17 15:01:45.034481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66961e25aa7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=55), nullable=False),
    sa.Column('last_name', sa.String(length=55), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('parcel_locker')
    op.drop_table('package')
    op.drop_table('locker')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('id_',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('id_',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('users')
    # ### end Alembic commands ###
